version: '3.5'

services:

  api:
    image: localhost:5000/quizmaster-api
    restart: always
    ports: 
      - 8080:8080
    depends_on:
      - mongodb
    environment:
      - PORT=8080
      - MONGODB_URI=mongodb://mongodb:27017/quizmaster
      - PASSWORD_ENCODER_SEED=password
      - JWT_SECRET=password
      - SPRING_PROFILES=primary,dev
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=password
      - SENDGRID_API_KEY=YOUR API KEY GOES HERE
      - PLAYER_LOGIN_URL=http://localhost:3000/#/autologin
      - CORS_WHITELIST=http://localhost:3000
      - SCORING_THRESHOLD_LOWER=0f
      - SCORING_THRESHOLD_UPPER=2.4f
      - CLOUDINARY_URL=YOUR URL GOES HERE
    networks:
      - quizmaster

  frontend:
    image: localhost:5000/quizmaster-frontend
    restart: always
    ports:
      - 3000:5000
    networks:
      - quizmaster

  mongodb:
    image: mongo:4.2
    volumes:
      - mongo_data:/data/db
    expose:
      - 27017
    networks:
      - quizmaster

volumes:
  mongo_data:
    driver: local

networks:
  quizmaster:
    driver: bridge
    name: quizmaster