version: '3'

services:

  api:
    build:
      context: ./quizmaster-api
    restart: always
    ports: 
      - 8080:8080
    depends_on:
      - mongodb
    environment: 
      - MONGODB_URI=mongodb://mongodb:27017
      - MONGODB_DATABASE_NAME=quizmaster
      - PASSWORD_ENCODER_SEED=password
      - JWT_SECRET=password
      - SPRING_PROFILES=primary,dev
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=password
      - SENDGRID_API_KEY=YOUR API KEY GOES HERE
      - PLAYER_LOGIN_URL=http://localhost:8080

  mongodb:
    image: mongo:4.0-xenial
    expose:
      - 27017