apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
    nodePort: 30001
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  lables:
    app: api
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: api
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: api
        image: localhost:5000/quizmaster-api:0.1.0
        imagePullPolicy: Never
        ports:
          - containerPort: 8080
        env:
          - name: MONGODB_URI
            value: mongodb://mongodb:27017
          - name: MONGODB_DATABASE_NAME
            value: quizmaster
          - name: PASSWORD_ENCODER_SEED
            value: password
          - name: JWT_SECRET
            value: password
          - name: SPRING_PROFILES
            value: primary,dev
          - name: ADMIN_USERNAME
            value: admin
          - name: ADMIN_PASSWORD
            value: password
          - name: SENDGRID_API_KEY
            value: YOUR API KEY GOES HERE
          - name: PLAYER_LOGIN_URL
            value: http://localhost:30001

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  lables:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:4.0-xenial
        ports:
          - containerPort: 27017